# Generated by Django 3.2.7 on 2021-09-22 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_bod', models.DateField()),
                ('client_monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loans.application')),
                ('approved_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collection_date', models.DateField()),
                ('next_collection_date', models.DateField()),
                ('collected_by', models.CharField(max_length=30)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.account')),
            ],
        ),
    ]
