# Generated by Django 3.2.7 on 2021-09-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_assign_account',
            field=models.BooleanField(default=False),
        ),
    ]
